apiVersion: 1
groups:
  - name: calorie-api-alerts
    rules:
      - alert: AppDown
        expr: up{job="calorie-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "L'instance de l'API Calorie Tracker est hors service"
          description: "L'instance {{ $labels.instance }} du job {{ $labels.job }} ne répond plus depuis 1 minute."

      - alert: HighErrorRate
        expr: (rate(http_requests_total{status_code=~"5.."}[1m]) / rate(http_requests_total[1m])) * 100 > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Taux d'erreur élevé détecté"
          description: "Le taux d'erreur 5xx dépasse 5% sur les 2 dernières minutes."
